export const GET_SHOPPING_CART = "GET_SHOPPING_CART";
export const ADD_PRODUCT_TO_SHOPPING_CART = "ADD_PRODUCT_TO_SHOPPING_CART";
export const UPDATE_PRODUCT_OFF_SHOPPING_CART = "UPDATE_PRODUCT_OFF_SHOPPING_CART";
export const DELETE_PRODUCT_OFF_SHOPPING_CART = "DELETE_PRODUCT_OFF_SHOPPING_CART";